@baseUrl = http://localhost:3333


GET {{baseUrl}}/ HTTP/1.1

###

POST {{baseUrl}}/users/register HTTP/1.1
Content-Type: application/json

{
    "email": "admin@g.com",
    "username": "Admin",
    "password": "admin123"
}

###

# @name login
POST {{baseUrl}}/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@g.com",
    "password": "admin123"
}

###

@authToken = {{login.response.body.token}}
GET {{baseUrl}}/protected HTTP/1.1
Authorization: Bearer {{authToken}}
